# Generated by Django 5.2.4 on 2025-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=300)),
                ('roll_no', models.IntegerField()),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
