# Generated by Django 5.2.4 on 2025-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('title', models.CharField(max_length=230)),
                ('is_avaliable', models.BooleanField(default=True)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Fantasy', 'Fantasy'), ('Biography', 'Biography'), ('Mystery', 'Mystery'), ('Other', 'Other')], default='Other')),
            ],
        ),
    ]
